app/models/blogs.py
class Blog:
    all_blogs = []

    # def __init__(self.blog):
    #     self.blog = blog

    def save_blog(self):
        Blog.all_blogs.append(self)

    @classmethod
    def clear_blogs(cls):
        Blog.all_blogs.clear()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Required


class BlogForm(FlaskForm):

    title = StringField('Review title', validators=[Required()])
    blog = TextAreaField('New Blog', validators=[Required()])
    submit = SubmitField('Submit')

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, StringField
from wtforms.validators import Required, DataRequired


class BlogForm(FlaskForm):
    title = StringField('New Blog', validators=[DataRequired()])
    body = TextAreaField('Enter your Blog here', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    comment = TextAreaField('Write a comment here',
                            validators=[DataRequired()])

    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail

from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


bootstrap = Bootstrap()
db = SQLAlchemy()

bootstrap = Bootstrap()

photos = UploadSet('photos', IMAGES)

mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # configure UploadSet
    configure_uploads(app, photos)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, errors


# def create_app(config_name):
#     app = Flask(__name__)

#     # Creating the app configurations
#     app.config.from_object(config_options[config_name])

#     # Initializing flask extensions
#     bootstrap.init_app(app)

#     # Registering the blueprint
#     from .main import main as main_blueprint
#     app.register_blueprint(main_blueprint)

#     return app

app/main/views.py
from flask import render_template, redirect, url_for, request, abort, flash
from . import main
from ..blogs import User, Blog, Comment
from .forms import UpdateProfile, BlogForm, CommentForm
from ..import db, photos
from flask_login import login_required, current_user


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)


@main.route('/')
@login_required
def index():

    return render_template('index.html')


@main.route('/pitch//new', methods=['GET', 'POST'])
@login_required
def new_blog():
    '''
       view function that defines the routes decorater for the pitch
        '''

    form = BlogForm()
    if form.validate_on_submit():
        blogs = Blog(title=form.title.data,
                     body=form.body.data, user_id=current_user.id)
        db.session.add(blogs)
        db.session.commit()
        flash('Your pitch has been created succesfully')
        return redirect(url_for('main.new_blog'))
    # title = "Create a Pitch"
    blogs = Blog.query.all()

    return render_template('new_blog.html', form=form, pitch_list=blogs)


@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)


@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/views.py
# from flask import render_template
# from app import app
# # from .models import blogs
# from .forms import BlogForm
# # Blog = blogs.Blog


# @app.route('/')
# def index():

#     return render_template('index.html')


# # @app.route('/blog/<int:blog_id>')
# # def blog(blog_id):

# #     return render_template('blog.html', id=blog_id)
# # @app.route('/blog/<int:id>') methods = ['GET', 'POST'])
# # def new_blog(id):
# #     form=BlogForm()

# #     if form.validate_on_submit():
# #         title=form.title.data
# #         blog=form.blog.data
# #         new_blog=Blog(title)
# #         new_blog.save_blog()

# #     return render_template('new_blog,html', title = title, blog_form = form)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
{% endblock %}


{% block content %}
<div class="container-fluid">
    <h1 class="text-center">Add a new blog</h1>
    <div class="row">
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        <div class="panel panel-default panel-heading"><a href="/pitch//new">Food</a></div>
        <div class="panel panel-default panel-heading"><a href="/pitch//new">Business</a></div>
        <div class="panel panel-default panel-heading"><a href="/pitch//new">Fashion</a></div>

    </div>
</div>
{{macro.displayBlogList(blog_list)}}

{% endblock%}

app/templates/macros.html
{% macro displayBlogList(blog_list) %}
{% for blog in blog_list %}
<div class="col-md-1">
</div>
<div class="col-md-10">
    <div class="card m-7">
        <div class="card-header">
            <h3 class="card-title">{{blog.title}}</h3>
        </div>
        <div class="card-body">
            <p class="card-text">{{blog.body}}</p>
        </div>
        <hr>
        <div class="card-footer">
            <a href="{{ url_for('main.new_comment') }}" class="btn btn-success btn-sm">Comment</a>

        </div>
    </div>
</div>
<div class="col-md-1">
</div>
{% endfor %}
{% endmacro %}
{% macro displayCommentList(comment_list)%}
{% for review in comment_list %}
<div class="col-md-3">
</div>
<div class="col-md-6">
    <p>{{review.comment}}</p>
</div>
<div class="col-md-3">
</div>
</div>

{% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li style="color:white;padding:15px;">{{current_user.username}}</li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                    {%endif%}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                    {%endif%}
                </ul>
            </button>
            <a class="navbar-brand" href="/"> Blog Post </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% import 'macros.html' as macro %}
{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}
{% block content %}

<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body.label(class="form-control-label") }}
                {% if form.body.errors %}
                {{ form.body(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.body(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

</div>

</div>

<hr>
<!-- Content block -->
<div class="container-fluid mt-3">
    <div class="row">
        {{macro.displayBlogList(blog_list)}}

    </div>
</div>

{% endblock content %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

{% if user == current_user %}
<a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
        </div>
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

            {%else%}
            <p>No profile picture</p>

            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}